# Generated by Django 4.0.6 on 2022-07-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('expires_in', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrname', models.CharField(max_length=100, verbose_name='Название')),
                ('color_primary', models.CharField(blank=True, max_length=7, null=True, verbose_name='Основной цвет')),
                ('color_button', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates', verbose_name='Изображение')),
                ('headline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('about_us', models.TextField(blank=True, max_length=100, null=True, verbose_name='О нас')),
                ('social_media_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа1')),
                ('title1', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url1', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('social_media_type2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа2')),
                ('title2', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url2', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('social_media_type3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа3')),
                ('title3', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url3', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('add_more', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительно')),
                ('welcome_screen', models.ImageField(blank=True, null=True, upload_to='templates', verbose_name='Экран приветствия')),
                ('feadback', models.TextField(blank=True, null=True, verbose_name='Отзывы')),
                ('imageforqr', models.ImageField(blank=True, null=True, upload_to='templates', verbose_name='Изображение для QR')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
                ('expires_in', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Scaner Counts')),
                ('tariff', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='qrgeneratorv.tariff')),
            ],
        ),
    ]
