# Generated by Django 4.0.6 on 2022-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название QR кода')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('image', models.FileField(blank=True, upload_to='qrcode')),
                ('expires_in', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Scaner Counts')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('expires_in', models.DurationField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrname', models.CharField(max_length=100, verbose_name='Название')),
                ('color_primary', models.CharField(blank=True, max_length=7, null=True, verbose_name='Основной цвет')),
                ('color_button', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates', verbose_name='Изображение')),
                ('headline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('about_us', models.TextField(blank=True, max_length=100, null=True, verbose_name='О нас')),
                ('social_media_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа1')),
                ('title1', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('social_media_type1_url_counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Тип медиа1 Scaner Counts')),
                ('social_media_type2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа2')),
                ('title2', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('social_media_type2_url_counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Тип медиа2 Scaner Counts')),
                ('social_media_type3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип медиа3')),
                ('title3', models.CharField(blank=True, default='Название', max_length=100, null=True, verbose_name='Название')),
                ('url3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка')),
                ('social_media_type3_url_counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='Тип медиа3 Scaner Counts')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
    ]
