# Generated by Django 4.0.6 on 2022-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='creation_count',
            field=models.IntegerField(default=3, help_text='Count of Creation', verbose_name='Количество созданий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='scan_count',
            field=models.IntegerField(default=4, help_text='Count of Scan', verbose_name='Количество сканирований'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='expires_in',
            field=models.DurationField(blank=True, help_text='по дням', null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Ценa в долларах', max_digits=10, verbose_name='Цена'),
        ),
    ]
