# Generated by Django 4.0.6 on 2022-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
