# Generated by Django 4.0.6 on 2022-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
