# Generated by Django 4.0.6 on 2022-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0002_tariff_creation_count_tariff_scan_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='scan_count',
            field=models.IntegerField(blank=True, help_text='Count of Scan', null=True, verbose_name='Количество сканирований'),
        ),
    ]
