# Generated by Django 4.0.6 on 2022-07-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0002_alter_qrcode_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='tariff',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='qrgeneratorv.tariff'),
        ),
    ]
