# Generated by Django 4.0.6 on 2022-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0002_alter_qrcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url_counter',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Scaner Counts'),
        ),
    ]
