# Generated by Django 4.0.6 on 2022-08-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0002_alter_qrcode_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='qrgeneratorv.tariff'),
            preserve_default=False,
        ),
    ]
