# Generated by Django 4.0.6 on 2022-08-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0003_user_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='admin_panel',
            field=models.BooleanField(default=False, verbose_name='Админ панель'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='sms_service',
            field=models.CharField(default=7, help_text='Date of SMS Cervice', max_length=100, verbose_name='Сервис отправки SMS'),
            preserve_default=False,
        ),
    ]
