# Generated by Django 4.0.6 on 2022-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0003_alter_qrcode_url_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
