# Generated by Django 4.0.6 on 2022-07-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0003_alter_qrcode_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='tariff',
        ),
    ]
