# Generated by Django 4.0.6 on 2022-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0005_smsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='sms_service',
            field=models.IntegerField(help_text='Date of SMS Cervice', verbose_name='Сервис отправки SMS'),
        ),
    ]
