# Generated by Django 4.0.6 on 2022-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0005_user_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='creation_count',
            field=models.IntegerField(default=0, help_text='Count of Creation', verbose_name='Количество созданий'),
        ),
    ]
