# Generated by Django 4.0.6 on 2022-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0005_alter_template_url1_alter_template_url2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.FileField(blank=True, upload_to='qrcode'),
        ),
    ]
