# Generated by Django 4.0.6 on 2022-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0006_alter_tariff_creation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('brown', 'brown'), ('purple', 'purple'), ('pink', 'pink'), ('yellow', 'yellow'), ('grey', 'grey'), ('light_blue', 'light_blue')], default='black', max_length=15),
        ),
        migrations.AlterField(
            model_name='qrcodefree',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('brown', 'brown'), ('purple', 'purple'), ('pink', 'pink'), ('yellow', 'yellow'), ('grey', 'grey'), ('light_blue', 'light_blue')], default='black', max_length=15),
        ),
        migrations.AlterField(
            model_name='template',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('brown', 'brown'), ('purple', 'purple'), ('pink', 'pink'), ('yellow', 'yellow'), ('grey', 'grey'), ('light_blue', 'light_blue')], default='black', max_length=15),
        ),
    ]
