# Generated by Django 4.0.6 on 2022-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0006_alter_tariff_sms_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='QR Kod içeriği')),
                ('scale', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=5, max_length=2)),
                ('color', models.CharField(choices=[('black', 'siyah'), ('red', 'kırmızı'), ('blue', 'mavi'), ('green', 'yeşil'), ('brown', 'kahverengi'), ('purple', 'mor'), ('pink', 'pembe'), ('yellow', 'sarı'), ('grey', 'gri'), ('light_blue', 'açık mavi')], default='black', max_length=15)),
            ],
        ),
    ]
