# Generated by Django 4.0.6 on 2022-08-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0007_alter_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(default=33, max_length=100, verbose_name='Название QR кода'),
            preserve_default=False,
        ),
    ]
