# Generated by Django 4.0.6 on 2022-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgeneratorv', '0007_qrcodefree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodefree',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Enter text or url'),
        ),
    ]
